name: Build CI

on:
  push:
    paths-ignore: '**.md'
  pull_request:
    paths-ignore: '**.md'

jobs:
  build:
    name: Build
    runs-on: macos-14
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Build with Gradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          ./gradlew assembleRelease
          ./gradlew --stop
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: KeyAttestation-CI_#${{ github.run_number }}
          path: app/build/outputs
